using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

public enum AppData : ushort
{
    Local = 0,
    Roaming = 1,
    LocalLow = 2
}

public enum RunMode
{
    Backup = 0,
    Restore
}

public struct CheckedItem
{
    public CheckedItem(String name)
    {
        Name = name;
        SubItem = new List<(String, CheckState)>();
    }

    public CheckedItem(String name, List<(String, CheckState)> subitem)
    {
        Name = name;
        SubItem = subitem;
    }

    public String Name { get; set; }
    public List<(String Name, CheckState State)> SubItem { get; set; }
};

public static class Global
{
    // These are some weird chains of function and method calls. So much for using assembly attributes...
    public static String appName = ((AssemblyTitleAttribute)Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyTitleAttribute), false)[0]).Title;
    public static String appVersion = ((AssemblyFileVersionAttribute)Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyFileVersionAttribute), false)[0]).Version;

    public static String LocalAppDataPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
    public static String RoamingAppDataPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
    public static String LocalLowAppDataPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "AppData", "LocalLow");
    public static String AppDataPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "AppData");

    public const String TempPath = "temp/";

    public static List<CheckedItem> checkedList = new List<CheckedItem>();

    public static AppData selectedAppData = AppData.Local;
    public static object? selectedItem = null;
}

public enum ErrorCode : ushort
{
    OK = 0,

    MiscException = 1,
    MiscDirectoryNotFound,
    MiscInvalidAppData,
    MiscTempDeletionFailed,
    MiscTempDeletionUnsafe,

    BackupException = 100,
    BackupEmptyFileName,
    BackupFolderNotFound,
    BackupSubFolderNotFound,
    BackupNoCheckedItems,
    BackupCancelled,

    RestoreException = 200,
    RestoreEmptyFileName,
    RestoreInvalidFile,
    RestoreFileUnknownFormat,
    RestoreCancelled,

    FetchDirException = 300
}

public class Utils
{
    public static DialogResult ShowErrorMsg(ErrorCode code, String exceptionMessage = "")
    {
        String caption = "";
        String message = "";
        MessageBoxButtons buttons = MessageBoxButtons.OK;
        MessageBoxIcon icon = MessageBoxIcon.Error;

        switch (code)
        {
            case ErrorCode.OK:
                caption = "Success";
                message = "The operation succeeded :)";
                icon = MessageBoxIcon.Information;
                break;

            case ErrorCode.MiscException:
                caption = "Error";
                message = $"Something failed: {exceptionMessage}";
                break;

            case ErrorCode.MiscDirectoryNotFound:
                caption = "Error";
                message = $"The selected item ({exceptionMessage}) was not found, maybe it was deleted?";
                break;

            case ErrorCode.MiscInvalidAppData:
                caption = "Error";
                message = "An invalid AppData type was selected. This is very weird and shouldn't happen. Please report this bug.";
                break;

            case ErrorCode.MiscTempDeletionFailed:
                caption = "Error";
                message = $"The temp folder could not be deleted. Manually deleting the \"temp\" folder located in the executable's directory may fix this. Please report this bug.\nException details: {exceptionMessage}";
                break;

            case ErrorCode.MiscTempDeletionUnsafe:
                caption = "Error";
                message = "The temp folder contains unknown files/folders, likely not generated by the program. Deleting the temp folder in this state could be dangerous!\nSelect \"Yes\" if you want to delete the folder anyways, otherwise select \"No\".";
                buttons = MessageBoxButtons.YesNo;
                break;

            case ErrorCode.BackupException:
                caption = "Backup failed";
                message = $"Backup failed: {exceptionMessage}";
                break;

            case ErrorCode.BackupEmptyFileName:
                caption = "Backup failed";
                message = "The file name cannot be empty.";
                break;

            case ErrorCode.BackupFolderNotFound:
                caption = "Backup failed";
                message = "One of the selected folders was not found, maybe it was deleted?";
                break;

            case ErrorCode.BackupSubFolderNotFound:
                caption = "Backup failed";
                message = "One of the subfolders inside a selected folder was not found, maybe it was deleted?";
                break;

            case ErrorCode.BackupNoCheckedItems:
                caption = "Backup failed";
                message = "No folder has been selected for backup yet.";
                break;

            case ErrorCode.BackupCancelled:
                caption = "Backup cancelled";
                message = "The backup operation has been cancelled, no backup file was created.";
                icon = MessageBoxIcon.Information;
                break;

            case ErrorCode.RestoreException:
                caption = "Restore failed";
                message = $"Restore failed: {exceptionMessage}";
                break;

            case ErrorCode.RestoreEmptyFileName:
                caption = "Restore failed";
                message = "No file has been selected.";
                break;

            case ErrorCode.RestoreInvalidFile:
                caption = "Restore failed";
                message = "The selected file is not a valid backup file.";
                break;

            case ErrorCode.RestoreFileUnknownFormat:
                caption = "Restore failed";
                message = "The selected file has an unknown format. It most likely wasn't created using this program.";
                break;

            case ErrorCode.RestoreCancelled:
                caption = "Restore cancelled";
                message = "The restore operation has been cancelled. Some folders may have been (partially) restored.";
                icon = MessageBoxIcon.Information;
                break;

            case ErrorCode.FetchDirException:
                caption = "Fetching directories failed";
                message = $"Fetching directories failed: {exceptionMessage}";
                break;
        }

        DialogResult res = MessageBox.Show(message, caption, buttons, icon);
        return res;
    }

    public static bool SafeDeleteTempFolder(bool force = false)
    {
        try
        {
            if (!Directory.Exists(Global.TempPath)) return true;

            if (Directory.GetDirectories(Global.TempPath).Count() == 0) return true;

            if (!force)
            {
                // Only recursively delete the temp folder if and only if an AppData folder is present
                string[] foldersToCheck = { "Local", "Roaming", "LocalLow" };
                foreach (String dir in Directory.GetDirectories(Global.TempPath))
                {
                    String newDir = Path.GetFileName(dir);

                    if (foldersToCheck.Contains(newDir)) continue;
                    if (Directory.GetDirectories(dir).Count() == 0) continue;

                    throw new UnauthorizedAccessException($"The temp folder contains an unknown file/folder: {dir}");
                }
            }

            Directory.Delete(Global.TempPath, true);
            return true;
        }
        catch (UnauthorizedAccessException)
        {
            DialogResult res = Utils.ShowErrorMsg(ErrorCode.MiscTempDeletionUnsafe);
            if (res == DialogResult.Yes)
                return SafeDeleteTempFolder(true);
            else
                return false;
        }
        catch (Exception ex)
        {
            Utils.ShowErrorMsg(ErrorCode.MiscTempDeletionFailed, ex.Message);
            return false;
        }
    }

    public static void CopyFile(String sourceDir, String destinationDir)
    {
        var file = new FileInfo(sourceDir);

        if (file.Attributes.HasFlag(FileAttributes.Hidden))
            return;

        String targetFilePath = Path.Combine(destinationDir, file.Name);
        file.CopyTo(destinationDir, true);
    }

    public static bool CopyDirectory(String sourceDir, String destinationDir, bool recursive, bool autoSkipFilesInUse = false ,bool verifyCheckState = false, bool inSubfolder = false)
    {
        // Get information about the source directory
        var dir = new DirectoryInfo(sourceDir);

        // Check if the source directory exists
        if (!dir.Exists)
        {
            if(!inSubfolder)
                ShowErrorMsg(ErrorCode.BackupFolderNotFound);
            else
                ShowErrorMsg(ErrorCode.BackupSubFolderNotFound);
            return true;
        }
        if (dir.Attributes.HasFlag(FileAttributes.Hidden))
        {
            // log "skipping hidden folder"
            return true;
        }

        // Cache directories before we start copying
        DirectoryInfo[] dirs = dir.GetDirectories();

        // Create the destination directory
        Directory.CreateDirectory(destinationDir);

        // Get the files in the source directory and copy to the destination directory
        foreach (FileInfo file in dir.GetFiles())
        {
            if (!inSubfolder)
            {
                if (Global.checkedList.Where(e => e.Name == file.DirectoryName)
                        .Any(e => e.SubItem
                        .Any(sub => sub.Name == file.Name && sub.State == CheckState.Unchecked))
                    )
                    continue;
            }
            if (file.Attributes.HasFlag(FileAttributes.Hidden)) // todo: toggleable option
                continue;

            bool retry;
            do
            {
                retry = false;

                try
                {
                    CopyFile(Path.Combine(sourceDir, file.Name), Path.Combine(destinationDir, file.Name));
                }
                catch (IOException ex)
                {
                    if (!autoSkipFilesInUse)
                    {
                        String caption = "Copy error";
                        String message = $"The file {file.FullName} could not be copied, most likely because it's being used by another process. Try closing any programs that may be using the file.\n" +
                                         $"Details: {ex.Message}\n" +
                                         "Abort to cancel the backup/restore process, Retry to try copying the file again or Ignore to skip this file.";
                        MessageBoxButtons buttons = MessageBoxButtons.AbortRetryIgnore;
                        MessageBoxIcon icon = MessageBoxIcon.Error;
                        DialogResult res = MessageBox.Show(message, caption, buttons, icon);

                        switch (res)
                        {
                            case DialogResult.Abort:
                                return false;

                            case DialogResult.Retry:
                                retry = true;
                                break;

                            case DialogResult.Ignore:
                                break;
                        }
                    }
                }
            } while (retry);
        }

        // If recursive and copying subdirectories, recursively call this method
        if (recursive)
        {
            foreach (DirectoryInfo subDir in dirs)
            {
                if (!inSubfolder && verifyCheckState)
                {
                    if (Global.checkedList.Where(e => e.Name == subDir.Parent!.FullName)
                        .Any(e => e.SubItem
                        .Any(sub => sub.Name == subDir.Name && sub.State == CheckState.Unchecked))
                    )
                        continue;
                }

                string newDestinationDir = Path.Combine(destinationDir, subDir.Name);
                bool success = CopyDirectory(subDir.FullName, newDestinationDir, true, autoSkipFilesInUse, verifyCheckState, true);
                if (!success) return false;
            }
        }

        return true;
    }

    public static bool CopyDirectoryWithLogging(BackgroundWorker worker, String sourceDir, String destinationDir, bool recursive, bool autoSkipFilesInUse = false, bool verifyCheckState = false, bool inSubfolder = false)
    {
        // Get information about the source directory
        var dir = new DirectoryInfo(sourceDir);

        // Check if the source directory exists
        if (!dir.Exists)
        {
            if (!inSubfolder)
                ShowErrorMsg(ErrorCode.BackupFolderNotFound);
            else
                ShowErrorMsg(ErrorCode.BackupSubFolderNotFound);
            return true;
        }
        if (dir.Attributes.HasFlag(FileAttributes.Hidden))
        {
            // log "skipping hidden folder"
            return true;
        }

        // Cache directories before we start copying
        DirectoryInfo[] dirs = dir.GetDirectories();

        // Create the destination directory
        Directory.CreateDirectory(destinationDir);

        // Get the files in the source directory and copy to the destination directory
        foreach (FileInfo file in dir.GetFiles())
        {
            if (!inSubfolder)
            {
                if (Global.checkedList.Where(e => e.Name == file.DirectoryName)
                        .Any(e => e.SubItem
                        .Any(sub => sub.Name == file.Name && sub.State == CheckState.Unchecked))
                    )
                    continue;
            }
            if (file.Attributes.HasFlag(FileAttributes.Hidden))
                continue;

            bool retry;
            do
            {
                retry = false;

                try
                {
                    worker.ReportProgress(-1, $"Copying file {file.Name} to {destinationDir}");

                    CopyFile(Path.Combine(sourceDir, file.Name), Path.Combine(destinationDir, file.Name));
                }
                catch (IOException ex)
                {
                    if (autoSkipFilesInUse)
                    {
                        worker.ReportProgress(-1, $"Skipped file {file.Name}");
                    }
                    else
                    {
                        String caption = "Copy error";
                        String message = $"The file {file.FullName} could not be copied, most likely because it's being used by another process. Try closing any programs that may be using the file.\n" +
                                         $"Details: {ex.Message}\n" +
                                         "Abort to cancel the backup/restore process, Retry to try copying the file again or Ignore to skip this file.";
                        MessageBoxButtons buttons = MessageBoxButtons.AbortRetryIgnore;
                        MessageBoxIcon icon = MessageBoxIcon.Error;
                        DialogResult res = MessageBox.Show(message, caption, buttons, icon);

                        switch (res)
                        {
                            case DialogResult.Abort:
                                worker.ReportProgress(-1, "Aborting");
                                return false;

                            case DialogResult.Retry:
                                retry = true;
                                break;

                            case DialogResult.Ignore:
                                worker.ReportProgress(-1, $"Skipped file {file.Name}");
                                break;
                        }
                    }
                    
                }
            } while (retry);
        }

        // If recursive and copying subdirectories, recursively call this method
        if (recursive)
        {
            foreach (DirectoryInfo subDir in dirs)
            {
                if (!inSubfolder && verifyCheckState)
                {
                    if (Global.checkedList.Where(e => e.Name == subDir.Parent!.FullName)
                        .Any(e => e.SubItem
                        .Any(sub => sub.Name == subDir.Name && sub.State == CheckState.Unchecked))
                    )
                        continue;
                }

                string newDestinationDir = Path.Combine(destinationDir, subDir.Name);
                bool success = CopyDirectoryWithLogging(worker, subDir.FullName, newDestinationDir, true, autoSkipFilesInUse, verifyCheckState, true);
                if (!success) return false;
            }
        }

        return true;
    }

    public static String GetAppDataString()
    {
        switch (Global.selectedAppData)
        {
            case AppData.Local: return "Local";
            case AppData.Roaming: return "Roaming";
            case AppData.LocalLow: return "LocalLow";
        }

        ShowErrorMsg(ErrorCode.MiscInvalidAppData);
        return "";
    }

    public static String GetAppDataPath()
    {
        switch (Global.selectedAppData)
        {
            case AppData.Local: return Global.LocalAppDataPath;
            case AppData.Roaming: return Global.RoamingAppDataPath;
            case AppData.LocalLow: return Global.LocalLowAppDataPath;
        }

        ShowErrorMsg(ErrorCode.MiscInvalidAppData);
        return "";
    }
}

